[package]
name = "rlox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror="1"
structopt = "0.3"
maplit="1"
once_cell="1"

[dev-dependencies]
assert_matches="1"
